apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv-claim
  namespace: airflow
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

