kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com 
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
#      appSecret:
#        secretName: datadog-secret
#        keyName: app-key
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      extraConfd:
        configDataMap:
          airflow.yaml: |-
            ad_identifiers:
              - airflow 
            init_config:
            instances:
              - url: http://airflow.cbioportal.dev.aws.mskcc.org           
